apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: kubernetes.io/basic-auth
stringData:
  username: postgresadmin
  password: postgrespwd
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  django-secret-key: 'django-insecure-h!vp_(%0@63%o&q04(^127a$i)$a%v1x6&(x8lb0f+r9!#qdj*'
